import { Inter } from 'next/font/google'
import Header from '../component/Header'
import "../style/global.css"
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-4xl" >
        <Link href="/"><Header /></Link>
        {children}
      
      </body>
    </html>
  )
}
